name: Verify code on push

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ {{ cookiecutter.version }} ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ '{{ matrix.python-version }}' }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ '{{ matrix.python-version }}' }}
      - name: Install pipeline dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox tox-poetry
      - name: Install package dependencies
        run: |
          poetry install
      - name: Run pipeline
        run: |
          poetry run tox
