repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: check-toml
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: poetry run check --fix
        language: system
        types: [ python ]
      - id: ruff-format
        name: ruff-format
        entry: poetry run format
        language: system
        types: [ python ]

